version: '3.8'

services:
  sql_server_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_container
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}
    volumes:
      - sqldata:/var/opt/mssql

  srt_backend:
    container_name: srt_backend_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Server=sql_server_db,1433;Database=DB_SRT;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;Encrypt=False;"
    depends_on:
      - sql_server_db

volumes:
  sqldata: