// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SRT.Infrastructure.Database;

#nullable disable

namespace SRT.Infrastructure.Migrations
{
    [DbContext(typeof(SrtDbContext))]
    [Migration("20251117222950_Reservation_And_Travel_Tables")]
    partial class Reservation_And_Travel_Tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "reservationstatus", new[] { "Pending", "Completed", "Canceled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "travelstatus", new[] { "Completed", "OnGoing", "Pending" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SRT.Domain.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Country", null, t =>
                        {
                            t.HasCheckConstraint("CK_Country_Id_uuid", "\"Id\" <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_Country_Name", "TRIM(\"Name\") <> ''");
                        });
                });

            modelBuilder.Entity("SRT.Domain.Entities.Destination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("StateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StateId", "Name")
                        .IsUnique();

                    b.ToTable("Destination", null, t =>
                        {
                            t.HasCheckConstraint("CK_Destination_Id_uuid", "\"Id\" <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_Destination_Name", "TRIM(\"Name\") <> ''");

                            t.HasCheckConstraint("CK_Destination_StateId_uuid", "\"StateId\" <> '00000000-0000-0000-0000-000000000000'");
                        });
                });

            modelBuilder.Entity("SRT.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("reservationstatus")
                        .HasDefaultValue("Pending");

                    b.Property<Guid>("TravelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("TravelId");

                    b.ToTable("Reservation", null, t =>
                        {
                            t.HasCheckConstraint("CK_Reservation_ClientId_uuid", "\"ClientId\" <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_Reservation_Id_uuid", "\"Id\" <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_Reservation_ReservationDate_timestamp", "\"ReservationDate\" <> '2023-01-01'::date");

                            t.HasCheckConstraint("CK_Reservation_TravelId_uuid", "\"TravelId\" <> '00000000-0000-0000-0000-000000000000'");
                        });
                });

            modelBuilder.Entity("SRT.Domain.Entities.ReservationDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid");

                    b.Property<short>("SeatNumber")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.ToTable("ReservationDetail", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReservationDetail_Id_uuid", "\"Id\" <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_ReservationDetail_ReservationId_uuid", "\"ReservationId\" <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_ReservationDetail_SeatNumber_uuid", "\"SeatNumber\" BETWEEN 1 AND 1000");
                        });
                });

            modelBuilder.Entity("SRT.Domain.Entities.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Rol", "Identity", t =>
                        {
                            t.HasCheckConstraint("CK_Rol_Id_uuid", "\"Id\" <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_Rol_Name", "TRIM(\"Name\") <> ''");
                        });
                });

            modelBuilder.Entity("SRT.Domain.Entities.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DestinationId1")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DistanceInKm")
                        .HasColumnType("numeric(10, 3)");

                    b.Property<TimeSpan>("EstimatedTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("FinalDestinationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OriginDestinationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("DestinationId1");

                    b.HasIndex("FinalDestinationId");

                    b.HasIndex("OriginDestinationId", "FinalDestinationId")
                        .IsUnique();

                    b.ToTable("Route", null, t =>
                        {
                            t.HasCheckConstraint("CK_Route_DistanceInKm_numeric", "\"DistanceInKm\" > 0");

                            t.HasCheckConstraint("CK_Route_EstimatedTime_interval", "\"EstimatedTime\" > interval '1 minute'");

                            t.HasCheckConstraint("CK_Route_FinalDestinationId_uuid", "\"FinalDestinationId\" <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_Route_Id_uuid", "\"Id\" <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_Route_OriginDestinationId_uuid", "\"OriginDestinationId\" <> '00000000-0000-0000-0000-000000000000'");
                        });
                });

            modelBuilder.Entity("SRT.Domain.Entities.State", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CountryId", "Name")
                        .IsUnique();

                    b.ToTable("State", null, t =>
                        {
                            t.HasCheckConstraint("CK_State_CountryId_uuid", "\"CountryId\" <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_State_Id_uuid", "\"Id\" <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_State_Name", "TRIM(\"Name\") <> ''");
                        });
                });

            modelBuilder.Entity("SRT.Domain.Entities.Travel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("travelstatus")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("RouteId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Travel", null, t =>
                        {
                            t.HasCheckConstraint("CK_Travel_ArrivalDate_timestamp", "\"ArrivalDate\" > '2023-01-01'::date");

                            t.HasCheckConstraint("CK_Travel_DepartureDate_timestamp", "\"DepartureDate\" > '2023-01-01'::date");

                            t.HasCheckConstraint("CK_Travel_DriverId_uuid", "\"DriverId\" <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_Travel_Id_uuid", "\"Id\" <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_Travel_Price_numeric", "\"Price\" > 0");

                            t.HasCheckConstraint("CK_Travel_RouteId_uuid", "\"RouteId\" <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_Travel_VehicleId_uuid", "\"VehicleId\" <> '00000000-0000-0000-0000-000000000000'");
                        });
                });

            modelBuilder.Entity("SRT.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("User", "Identity", t =>
                        {
                            t.HasCheckConstraint("CK_User_Email", "TRIM(\"Email\") <> ''");

                            t.HasCheckConstraint("CK_User_Id_uuid", "\"Id\" <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_User_Name", "TRIM(\"Name\") <> ''");

                            t.HasCheckConstraint("CK_User_Password", "TRIM(\"Password\") <> ''");

                            t.HasCheckConstraint("CK_User_Surname", "TRIM(\"Surname\") <> ''");

                            t.HasCheckConstraint("CK_User_Username", "TRIM(\"Username\") <> ''");
                        });
                });

            modelBuilder.Entity("SRT.Domain.Entities.UserRol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("UserId", "RolId")
                        .IsUnique();

                    b.ToTable("UserRol", "Identity", t =>
                        {
                            t.HasCheckConstraint("CK_UserRoles_Id_uuid", "\"Id\" <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_UserRoles_RolId_uuid", "\"RolId\" <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_UserRoles_UserId_uuid", "\"UserId\" <> '00000000-0000-0000-0000-000000000000'");
                        });
                });

            modelBuilder.Entity("SRT.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<short>("Capacity")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RegistrationPlate")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationPlate")
                        .IsUnique();

                    b.ToTable("Vehicle", null, t =>
                        {
                            t.HasCheckConstraint("CK_Vehicle_Capacity_smallint", "\"Capacity\" BETWEEN 1 AND 1000");

                            t.HasCheckConstraint("CK_Vehicle_Id_uuid", "\"Id\" <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_Vehicle_Model_varchar", "TRIM(\"Model\") <> ''");

                            t.HasCheckConstraint("CK_Vehicle_RegistrationPlate_varchar", "TRIM(\"RegistrationPlate\") <> ''");
                        });
                });

            modelBuilder.Entity("SRT.Domain.Entities.Destination", b =>
                {
                    b.HasOne("SRT.Domain.Entities.State", "State")
                        .WithMany("Destinations")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("SRT.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("SRT.Domain.Entities.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("SRT.Domain.Entities.Travel", "Travel")
                        .WithMany()
                        .HasForeignKey("TravelId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Travel");
                });

            modelBuilder.Entity("SRT.Domain.Entities.ReservationDetail", b =>
                {
                    b.HasOne("SRT.Domain.Entities.Reservation", "Reservation")
                        .WithMany("ReservationDetails")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("SRT.Domain.Entities.Route", b =>
                {
                    b.HasOne("SRT.Domain.Entities.Destination", null)
                        .WithMany("FinalRoutes")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SRT.Domain.Entities.Destination", null)
                        .WithMany("OriginRoutes")
                        .HasForeignKey("DestinationId1")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SRT.Domain.Entities.Destination", "FinalDestination")
                        .WithMany()
                        .HasForeignKey("FinalDestinationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("SRT.Domain.Entities.Destination", "OriginDestination")
                        .WithMany()
                        .HasForeignKey("OriginDestinationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("FinalDestination");

                    b.Navigation("OriginDestination");
                });

            modelBuilder.Entity("SRT.Domain.Entities.State", b =>
                {
                    b.HasOne("SRT.Domain.Entities.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("SRT.Domain.Entities.Travel", b =>
                {
                    b.HasOne("SRT.Domain.Entities.User", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("SRT.Domain.Entities.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("SRT.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Route");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("SRT.Domain.Entities.UserRol", b =>
                {
                    b.HasOne("SRT.Domain.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("SRT.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SRT.Domain.Entities.Country", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("SRT.Domain.Entities.Destination", b =>
                {
                    b.Navigation("FinalRoutes");

                    b.Navigation("OriginRoutes");
                });

            modelBuilder.Entity("SRT.Domain.Entities.Reservation", b =>
                {
                    b.Navigation("ReservationDetails");
                });

            modelBuilder.Entity("SRT.Domain.Entities.State", b =>
                {
                    b.Navigation("Destinations");
                });
#pragma warning restore 612, 618
        }
    }
}
