# @name api/authentication/login/
POST {{SRT_HostAddress}}/api/authentication/login
Content-Type: application/json

{
  "username": "bgaitan",
  "password": "mortadela01"
}

> {%
    client.global.set("auth_token", response.body.data.token);
%}

###

# @name api/users/register
POST {{SRT_HostAddress}}/api/users/register
Content-Type: application/json

{
  "name": "Brian Antonio",
  "surname": "Gaitán Corea",
  "username": "bgaitan",
  "password": "mortadela01",
  "email": "test@hotmail.com",
  "phoneNumber": "12345678"
}

### 

# @name api/users/info
GET {{SRT_HostAddress}}/api/users/info
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###

# @name api/countries?countryId
GET {{SRT_HostAddress}}/api/countries?countryId=f8ab24c1-3ac7-45d8-9831-40ccef5deff9
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###

# @name api/countries?countryName
GET {{SRT_HostAddress}}/api/countries?countryName=Nicaragua
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###

# @name api/countries/all
GET {{SRT_HostAddress}}/api/countries/all
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###

# @name api/countries/create
POST {{SRT_HostAddress}}/api/countries/create
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "countryName": "Nicaraguaaaaa"
}

###

# @name api/countries/update
PUT {{SRT_HostAddress}}/api/countries/update
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "countryId": "853fc4a4-93d1-4ba3-86e5-c67c82ae0015",
  "countryName": "Nicaragua"
}

###

# @name api/states
GET {{SRT_HostAddress}}/api/states?departamentoName=Managua
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###

# @name api/states/all
GET {{SRT_HostAddress}}/api/states/all?paisId=1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###

# @name api/states/create
POST {{SRT_HostAddress}}/api/states/create
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "countryId": "853fc4a4-93d1-4ba3-86e5-c67c82ae0015",
  "stateName": "Managua"
}

###

# @name api/states/update
PUT {{SRT_HostAddress}}/api/states/update
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "stateId": "3248c6df-cd63-4b12-8c0a-0717e4060166",
  "countryId": "853fc4a4-93d1-4ba3-86e5-c67c82ae0015",
  "stateName": "Managua"
}

###

# @name api/locaciones
GET {{SRT_HostAddress}}/api/locaciones?locacionName=Salvador Allende
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###

# @name api/locaciones/all
GET {{SRT_HostAddress}}/api/locaciones/all?departamentoId=1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###

# @name api/locaciones/create
POST {{SRT_HostAddress}}/api/locaciones/create
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "departamentoId": 1,
  "locacionName": "Salvador Allende"
}

###

# @name api/locaciones/update
PUT {{SRT_HostAddress}}/api/locaciones/update
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "locacionId": 1,
  "departamentoId": 1,
  "locacionName": "Malecon"
}

###

# @name api/locaciones/{locacionId}/delete
DELETE {{SRT_HostAddress}}/api/locaciones/1/delete
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###

# @name api/locaciones/{locacionId}/reactive
PATCH {{SRT_HostAddress}}/api/locaciones/1/reactive
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###

# @name api/vehiculos
GET {{SRT_HostAddress}}/api/vehiculos?placa=BAGC0001
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###

# @name api/vehiculos/all
GET {{SRT_HostAddress}}/api/vehiculos/all
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###

# @name api/vehiculos/create
POST {{SRT_HostAddress}}/api/vehiculos/create
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "placa": "BAGC0001",
  "modelo": "Kia Picanto",
  "capacidad": 10
}

###

# @name api/vehiculos/update
PUT {{SRT_HostAddress}}/api/vehiculos/update
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "vehiculoId": 1,
  "placa": "BAGC0001",
  "modelo": "Kia",
  "capacidad": 10
}

###

# @name api/vehiculos/{vehiculoId}/delete
DELETE {{SRT_HostAddress}}/api/vehiculos/1/delete
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###

# @name api/vehiculos/{vehiculoId}/reactive
PATCH {{SRT_HostAddress}}/api/vehiculos/1/reactive
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###

# @name api/rutas
GET {{SRT_HostAddress}}/api/rutas?rutaId=12
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###

# @name api/rutas/all
GET {{SRT_HostAddress}}/api/rutas/all
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###

# TODO se debe de revisar como se recibirá el campo Tiempo Estimado
# @name api/rutas/create
POST {{SRT_HostAddress}}/api/rutas/create
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "locacionOrigenId": 1,
  "locacionDestinoId": 1,
  "distanciaKm": 10.2,
  "tiempoEstimado": "16:15:00"
}

###

# @name api/rutas/update
PUT {{SRT_HostAddress}}/api/rutas/update
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "rutaId": 1,
  "locacionOrigenId": 1,
  "locacionDestinoId": 1,
  "distanciaKm": 10.3,
  "tiempoEstimado": "18:15:00"
}

###

# @name api/rutas/{rutaId}/delete
DELETE {{SRT_HostAddress}}/api/rutas/1/delete
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###

# @name api/rutas/{rutaId}/reactive
PATCH {{SRT_HostAddress}}/api/rutas/1/reactive
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###

# @name api/viajes/all
GET {{SRT_HostAddress}}/api/viajes/all
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###

# @name api/viajes/create
POST {{SRT_HostAddress}}/api/viajes/create
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "rutaId": 1,
  "vehiculoId": 1,
  "conductorId": 1,
  "costo": 120,
  "FechaHoraSalida": "2025-08-01",
  "FechaHoraLlegada": "2025-08-01"
}

###

# @name api/reservas/detalle
GET {{SRT_HostAddress}}/api/reservas/detalle?viajeId=1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###

# @name api/reservas/user?userId=1
GET {{SRT_HostAddress}}/api/reservas/user?userId=1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###

# @name api/reservas/create
POST {{SRT_HostAddress}}/api/reservas/create
Content-Type: application/json
Authorization: Bearer {{auth_token}}